name = "LEFT_registry"
uuid = "ffdbe137-4527-4a5c-bec7-d3ec4f761037"
repo = "ssh://git@github.com/cjwinstead/LEFT_registry"
description = "Julia registry for LEFT Lab projects."

[packages]
16d751f2-2168-46b0-9d00-9e1470832ba3 = { name = "NgHerb", path = "N/NgHerb" }
